#!/bin/bash
runValue=0
check="message"

function exists()
{
	program=$1
	if [ hash "$program" >/dev/null 2>&1 ]; then
		echo >&2 "$program is not found. Please install to continue"
		exit 1 
	fi;
}

function implementChecks()
{
	result=$1
	if [ "$result" -ne "0" ] ; then 
		echo "$file: failed check"
		echo "$check"
		runValue=1
	fi;
}

function verifyShellScripts()
{
	exists "shellcheck"
	file=$1
  	check=$(shellcheck "$file")
		implementChecks "$?" 
	return $runValue
}

function verifyPythonScripts()
{
	exists "pylint"
	file=$1 
	check=$(pylint "$file")
		implementChecks "$?"
	return $runValue 
}

function verifyGoScripts()
{
	exists "goimports" 
	file=$1
	goimports -w $file
}

for i in $(git diff --cached --name-only --diff-filter=ACM); do
	input=${i:(-3)}
	if [ "$input" == ".sh" ] ; then 
		verifyShellScripts "$i"
	elif [ "$input" == ".py" ] ; then
		verifyPythonScripts "$i"
	elif [ "$input" == ".go" ] ; then
		verifyGoScripts "$i" 
	fi;
done

if [ "$runValue" -eq "1" ] ; then
	echo "Commit Failed"
	 exit 1
else
	 exit 0
fi;
