#!/bin/bash

runValue=0
check=0
function implementChecks()
{
	result=$1
	if [ "$result" -ne "0" ] ; then 
		echo "$file: failed check"
		echo "$check"
		runValue=1
	fi;
}

function verifyShellScripts()
{
  file=$1
  check=$(shellcheck $file)
	implementChecks $? 
	return $runValue
}

function verifyPythonScripts()
{
  file=$1 
  check=$(pylint $file)
	implementChecks $?
	return $runValue 
}

for i in `git diff --cached --name-only --diff-filter=ACM`; do
	input=${i:(-3)}
	if [ "$input" == ".sh" ] ; then 
		verifyShellScripts $i
	elif [ "$input" == ".py" ] ; then
		verifyPythonScripts $i
	fi;
done

if [ "$runValue" -eq "1" ] ; then
	echo "Commit Failed"
	 exit 1
else
	 exit 0
fi;
